repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]

      - id: security-scan
        name: security scan
        entry: bandit -r . -x venv,.venv,env,.env,__pycache__,.git,node_modules
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]
